language: node_js
sudo: false
node_js:
- '5'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - wine
    - libusb-1.0-0-dev
    - libcups2-dev
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.npm"
env:
  global:
  - CXX=g++-4.8
before_install:
- npm install -g npm@latest --quiet
- npm list -g node-gyp --depth=0 || npm install -g node-gyp@latest --quiet
install:
- npm prune
- npm install
script:
- npm test
after_success:
after_failure:
notifications:
  slack:
    secure: Ya8etdkt+PX25UhrSgCsGpmiJ7cJD59erzr1eTF8wd9QkiJtO3MKECQE1+GreVJ04R63ROHu9Js1oYahJ8B/7LnstS7GQj3QJbLuA/C84v6wazhYFJl3/XjoyWU+zFIdtFxZB3h+YB6d1tGxOOIuMf/o9Inn7iR0lM1B5p+Fj7r7Cdf44QtSHlDc4QUL0/R6qf6aqWzTSCUo44ASV7C2YeFhrZnl+3CjsZGAk6IEzn2ABoSFNTNt3o1bEpTIg2DLFnBY9MY3gY3xhDyaCtIpRzYVcDU+wimU78iHBPJXSb0V83avR8eyC5+xQbcw8sIYbYUqLtWxkyt4xQKrhJF/hR/2YgjoKaqvCHKNtb+1jC5wzoNAuE107d8mpptZaLg0OUZEfk4vpKtY0/oCAH/X+/PNTRaeoMnwAJZy1vOATrG4JyEflEn+Gu79SuGy1WGes1zsr1LjASpzn4/BOKPmp/8ON8yB1bFObJZ0RBI/Xf79Nawf+ExyoR2odJFUipWsSdbY2yIMJGkZp3GU8Qv5FUFxSRD1OQCPLuiJwyvmV80ZrzicW+Eccii+/VuNGE+Lec+jOBhx1mbag2/ypwJqk2hFpzlzwgN+lE6ngbe7CSak2MzjuMXWZ8k9nrJoJORhBFerUFdrgecQTcadWABtL0y72kiwxRBbjWGFLBuedn4=
before_deploy:
  - npm run package-darwin
  - npm run package-linux
  - ./package-release.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TfEZc0nsRn8OH0NWqMOButIvnw1e0KfCeNkhHj9I8qc52J5RY4Iv6sRdLjV99/Krltp9M03kdrWLRf0q6rdq+tk6cWfFZcQHwb3WVD6qBEiFtruq7+8Z8T+UrjAJ1Ct/YPLyydY7ABX4Tl4LqJCwlLmknn9N4DzL/v93e7IVFVKh+jIT6bJ8+oYIQKo7X12gESUsXqWluxaCcHijMIk/w7ajja0B8JqpQ0S+4Ck6K0U3O5lsO/CNdO4UNXXAkKi82OR/8H9nHPuLh/iWJK27BaDgJ+ScMavFnlcoFHy0JFrYlXiXiyk4wX8EzVlsb5mELubZ2cqLRdftiodwmISjX37rjGP7FtA11KZcQvpz7dLmLEZRd66RT4GwN3vmV9k/+e1tA/Lww8+cmEvPPZRIN4LwvQCbYRk9oA3ITf/wR3rOG5jtsCbVmPxpgEzA+t+tikoenIH0nWPNsjYBDrbE5meTd5LvlFa/EzG2hyNjHwRy+PMS5mufTuNkdWmreJ8hgnKQs8AjbEvHOuqREYpeMWADyM77Jw3FbfufMRxQy2L2gGHaiZQ7OtywLL7E9AmtGKIq/f46V4ynPWd5BAnS0LFnAhoU5aujhf/pQrS23MX7VGS1CzT/s5JGOS6IwuwmugONZSjJEyo/ZOw1UjQjWfJIZA9AihsyAXq9YiDdDK0=
  file:
    - release/darwin-x64.tar.gz
    - release/linux-x64.tar.gz
    - release/win-x64.tar.gz
  on:
    tags: true
    all_branches: true
